### PR TITLE
Implement dispatcher support in journal and object store

### PR DESCRIPTION
**Pull request by alexguzun**
**Depends on** 
- https://github.com/vlingo/vlingo-symbio/pull/14

### CODE REVIEW

**Comment by alexguzun** [comment]
@VaughnVernon Yes, I have seen that. That's why I persist the `Dispatchable` entries toghether with the `Dispatchable`: https://github.com/vlingo/vlingo-symbio-geode/pull/6/files#diff-32ad60fa2c99fe4b0f43a968cb2a2835R72

**Comment by DaveMuirhead** [comment]
Hi Alex -

Haven’t looked at your pull request yet, but is this task in the Release project still relevant given your pull request?

https://github.com/orgs/vlingo/projects/12#card-19781411

From a quick glance at your change set it looks maybe like you decided to persist Entries with Dispatchables in the same region (?).

Best regards,

Dave

--------

Dave Muirhead
Blue River Systems Group, LLC
http://www.brsg.biz
dave@brsg.biz
303-638-4618 Mobile
303-309-6242 Office
303-309-6243 Fax

**Comment by alexguzun** [comment]
Hi  @DaveMuirhead. Yes it's still relevant and you are right, I am persisting the entities ( and the state ) in the same region as Dispatchable. This allows reusing the same dispatchable persistence logic for all stores (Journal, Object and State)

**Comment by DaveMuirhead** [comment]
Ah, you said entities not entries. I understand. Thank you

--------

Dave Muirhead
Blue River Systems Group, LLC
http://www.brsg.biz
dave@brsg.biz
303-638-4618 Mobile
303-309-6242 Office
303-309-6243 Fax

**Comment by alexguzun** [comment]
You are right. It's Entries.
```
      GeodeDispatchable<State<?>> instance = (GeodeDispatchable<State<?>>) o;
      out
      out
        .writeString("originatorId", instance.originatorId
        .writeObject("createdAt", instance.createdAt)
        .writeString("id", instance.id)
        .writeString("id", instance.id());
        .writeObject("state", instance.state);

      if (instance.state().isPresent()){
        out.writeObject("state", instance.state().get());
      }

      if (instance.entries()!=null && !instance.entries().isEmpty()){
        out.writeObjectArray("entries", instance.entries().toArray(new Entry[0]));
      }
```

**Comment by DaveMuirhead** [comment]
Do the Entries ever end up in their own table/region? Or do they remain persistent as part the Dispatchable?

--------

Dave Muirhead
Blue River Systems Group, LLC
http://www.brsg.biz
dave@brsg.biz
303-638-4618 Mobile
303-309-6242 Office
303-309-6243 Fax

**Comment by alexguzun** [comment]
As part of `Dispatchable`.

**Comment by VaughnVernon** [comment]
@DaveMuirhead In trying to support reliable consumption of post-persistence state and events @alexguzun suggested harmonizing all of the symbio components, including the use of `Dispatchable` across all persistence types. There is a lot of dust in the air right now but it's the right approach and will pay dividends soon.

@alexguzun Is there any attempt at ordering of `Dispatchable` instances?

**Comment by alexguzun** [comment]
@VaughnVernon The `Dispatchable` instances are dispatched in the same order as write operations, that originate the instance.
 On redispatched the instances will be orderdered by `io.vlingo.symbio.store.dispatch.Dispatchable#createdOn`

**Comment by VaughnVernon** [comment]
@alexguzun Excellent. It may be that time order resolution is not perfect since many Dispatchable instances could be written in the same millisecond, but at least causal order (on most occasions) will be preserved. It's probably near to impossible that Dispatcables in the same long-running process would write from multiple entities in the same millisecond.

**Comment by DaveMuirhead** [comment]
> @DaveMuirhead In trying to support reliable consumption of post-persistence state and events @alexguzun suggested harmonizing all of the symbio components, including the use of `Dispatchable` across all persistence types. There is a lot of dust in the air right now but it's the right approach and will pay dividends soon.
> 
> @alexguzun Is there any attempt at ordering of `Dispatchable` instances?

@VaughnVernon @alexguzun That all sounds good. The task regarding Geode transactions is relevant only if we need to persist entity state and associated entries in two separate Geode regions in a transactionally consistent way. If that's necessary (still) then there's details...Geode transactions require co-location of participating regions, etc.

**Comment by alexguzun** [comment]
@DaveMuirhead. Persisting Entries on the same region as dispatchable was a decision I have made just because the actual persistence in separate region was a task in progress. 
Other solution would be to persist just the ID's of Entries on dispatchable regions, and when retrieving the dispatch able,  get the entries from their region.

**Comment by VaughnVernon** [comment]
@DaveMuirhead @alexguzun The `Dispatchable` persistence could be used to create a separate region with near-total-ordering of `Entry` instances. Basically it would be used the same way as as `Projection` and `Exchange` feeds. It's eventually consistent, but I think from a `DomainEvent` (and persisted `Command`) standpoint this is more than acceptable.

**Comment by DaveMuirhead** [comment]
> @DaveMuirhead @alexguzun The `Dispatchable` persistence could be used to create a separate region with near-total-ordering of `Entry` instances. Basically it would be used the same way as `Projection` and `Exchange` feeds. It's eventually consistent, but I think from a `DomainEvent` (and persisted `Command`) standpoint this is more than acceptable.

@VaughnVernon are you referring to the strategy we talked about a while back where, after persistence of the Dispatchable and its aggregated events/commands there is an asynchronous process (async event listener, most likely) that copies the domain events and commands from the Dispatchable into a separate region?

**Comment by VaughnVernon** [comment]
@DaveMuirhead Yes. Does that seem correct? Also a Long region singleton could be used to assign total ordering.

**Comment by DaveMuirhead** [comment]
@vaughnvernon that should work fine. Regarding the Long region, you’re referring to a single Long-valued sequence from which event id’s can be allocated, correct? If so, yes that was my thought and plan, as well.

**Comment by VaughnVernon** [comment]
@DaveMuirhead Maybe I have it wrong, but I thought that the Entry region would have a singleton Long. I didn't think that the Long would be in its own region (maybe you mistyped).

**Comment by DaveMuirhead** [comment]
@VaughnVernon I may not be understanding, but Geode doesn't have any built-in ID generator or auto-sequence key type. Keys and values are whatever type you choose. But there's a Long ID generator already checked in (`io.vlingo.symbio.store.common.geode.identity.LongIDGenerator`) and working, which is a variation of the one I've used for years. It relies on a region whose entries are sequence name / sequence value pairs. So, we'd have one entry in the ID sequences region for Entries that is the monotonically increasing, Long value that represents the last ID allocated. Hope that makes sense.

**Comment by VaughnVernon** [comment]
@DaveMuirhead Thanks, I think we are saying the same things. Graphically, I see it as two regions, one for `Dispatchable` and one for `Entry`:

`Dispatchable: [c+ms=D] [r+ms=D] [f+ms=D] [a+ms=D] ... [s+ms=D]`

`             Entry: [1=E] [2=E] [3=E] [w]    [ID=4]`

In `Dispatchable` the `?+ms` means the unique id assigned to the D along with the time in milliseconds.

In `Entry` the `[w]` represents the next write/put key-value into the region. The `ID` is the key of the `Long` value that holds the next sequence number to be used to write where the `w` is.

I may be wrong but I have envisioned the writer into the `Entry` region to be a Geode `Function` so that each `D` value doesn't have to be read back to the application/service node in order to write to the `Entry` region.

**Comment by DaveMuirhead** [comment]
Oh, I see what you mean. Yeah, there’s no constraint that the keys and values of a region have to be homogenous, so could store the ID in the entry region. That’s fine.

**Comment by DaveMuirhead** [comment]
@alexguzun I’m not sure if you’re waiting for a review from me or if you have more to do given the build failures. Let me know. I have some work to do after you merge (not intended to rush or pressure you, just coordinating).

**Comment by alexguzun** [comment]
Hi @DaveMuirhead . The build is failing because it depends on https://github.com/vlingo/vlingo-symbio/pull/14. 

Your review would be highly appreciated considering it has implications for you.

**Comment by VaughnVernon** [comment]
@DaveMuirhead I am leaving this open pending your review. I didn't find problems previously, but you may. The merge is yours to approve and perform.

**Pull request merged**
